#pragma once
#include <string>
#include <streambuf>
#include <x86intrin.h>
#include <ctime>
#include <stdio.h>
#include <sys/types.h>
#include <fcntl.h>
#include <unistd.h>
#include <stdlib.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <netdb.h>
#include <arpa/inet.h>
#include <endian.h>
#include <errno.h>
#include <signal.h>
#include <sys/select.h>
#include <iostream>
#include "types.h"
